trigger:
- main  # or your main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true

# ✅ Add this BEFORE installing requirements.txt
- script: |
    python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install Build Tools'

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Optional: test or deploy
# - script: pytest tests/
#   displayName: 'Run tests'
