steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    python -m pip install --upgrade pip setuptools wheel
  displayName: '✅ Install Build Tools'

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'
